### ISSUE TITLE
Get errors making the build

### ISSUE THREAD

**Issue by dpggit** [ViveSoftware/ViveFoveatedRendering#4]
It gives errors when making the build using Unity 2018.2.11

Gives several errors like this :
Assets\ViveFoveatedRendering\Scripts\ViveFoveatedVisualizer.cs(94,17): error CS0234: The type or namespace name 'PlayerSettings' does not exist in the namespace 'UnityEditor' (are you missing an assembly reference?)

**Comment by kyo8568131** [comment]
Hi dpggit,
Thanks for your response, we will fix it and update in the next patch.
Before that, you could replace the rendering mode judgment with "XRSettings.stereoRenderingMode" in both ViveFoveatedRendering.cs and ViveFoveatedVisualizer.cs.

**Comment by XpertVR** [comment]
Hi, having the exact same problem! Where exactly would we be replacing the rendering mode judgment? Can't find it for the life of me.
